// <auto-generated />
using CityInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityInfo.API.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    [Migration("20230102172713_Update entries")]
    partial class Updateentries
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Continent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageAltText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Continent = "North America",
                            Country = "United States",
                            Description = "New York is composed of five boroughs – Brooklyn, the Bronx, Manhattan, Queens and Staten Island - is home to 8.4 million people who speak more than 200 languages, hail from every corner of the globe, and, together, are the heart and soul of the most dynamic city in the world.",
                            ImageAltText = "An image showing an aerial view of the New York skyline on a sunny afternoon.",
                            ImageUrl = "https://thumbs.dreamstime.com/b/new-york-skyline-sunny-afternoon-aerial-view-53728429.jpg",
                            Name = "New York City"
                        },
                        new
                        {
                            Id = 2,
                            Continent = "Europe",
                            Country = "United Kingdom",
                            Description = "Noisy and vibrant, London is a megalopolis of people, ideas and frenetic energy. The capital and largest city of England, and of the wider United Kingdom, it is also the largest city in Western Europe. Situated on the River Thames in South-East England, Greater London has an official population of a little over 8 million, but the estimate of between 12 and 14 million people in the greater metropolitan area better reflects its size and importance.",
                            ImageAltText = "An image showing Tower Bridge on an evening with dark clouds.",
                            ImageUrl = "https://thumbs.dreamstime.com/b/tower-bridge-london-uk-38138737.jpg",
                            Name = "London"
                        },
                        new
                        {
                            Id = 3,
                            Continent = "Europe",
                            Country = "France",
                            Description = "Paris has the reputation of being the most beautiful and romantic of all cities, brimming with historic associations and remaining vastly influential in the realms of culture, art, fashion, food and design.",
                            ImageAltText = "A picture of the Eiffel Tower at sundown.",
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/04/25/09/26/eiffel-tower-3349075__480.jpg",
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 4,
                            Continent = "North America",
                            Country = "United States",
                            Description = "A major city and commercial hub in North Carolina. Its modern city center (Uptown) is home to the Levine Museum of the New South, which explores post–Civil War history in the South, and hands-on science displays at Discovery Place.",
                            ImageAltText = "An image showing a series of North Carolina skylines.",
                            ImageUrl = "https://media.istockphoto.com/id/1276994658/photo/fall-in-charlotte-nc.jpg?b=1&s=170667a&w=0&k=20&c=yI0cUp8q2xSHF8szoQIv5sVpAAQekyqMtv0FBQZermY=",
                            Name = "Charlotte"
                        },
                        new
                        {
                            Id = 5,
                            Continent = "Europe",
                            Country = "United Kingdom",
                            Description = "Huntingdon is a market town in the Huntingdonshire district in Cambridgeshire, England. The town was given its town charter by King John in 1205. It was the county town of the historic county of Huntingdonshire. Oliver Cromwell was born there in 1599 and became one of its Members of Parliament in 1628.",
                            ImageAltText = "An image showing Huntingdon Town Centre in the morning.",
                            ImageUrl = "https://www.harveyrobinson.co.uk/xml/cache/mceimages/hr-Huntingdon-Landmark.jpg",
                            Name = "Huntingdon"
                        },
                        new
                        {
                            Id = 6,
                            Continent = "Europe",
                            Country = "France",
                            Description = "Brest is a port city in Brittany, in northwestern France, bisected by the Penfeld river. It’s known for its rich maritime history and naval base. At the mouth of the Penfeld, overlooking the harbor, is the National Navy Museum, housed in the medieval Château de Brest.",
                            ImageAltText = "An image showing a busy part of the City.",
                            ImageUrl = "https://images.france.fr/zeaejvyq9bhj/417nfQFcHe0uuuoMw2AoIO/874bf93f75529a0801d33f1c5d7dff0c/resizedshutterstock_151480559_place-ste-anne-rennes.jpg",
                            Name = "Brest"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageAltText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointsOfInterests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "Central Park is an urban park in New York City located between the Upper West and Upper East Sides of Manhattan. It is the fifth-largest park in the city, covering 843 acres.",
                            ImageAltText = "A morning taken directly in Central Park.",
                            ImageUrl = "https://media.istockphoto.com/id/1309037300/photo/central-park-in-spring.jpg?b=1&s=170667a&w=0&k=20&c=nTMGmhXEwkB_s9gglwFX9qz74RbjG9caQryz36l02Sc=",
                            Name = "Central Park"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            Description = "Tower Bridge is a Grade I listed combined bascule and suspension bridge in London, built between 1886 and 1894, designed by Horace Jones and engineered by John Wolfe Barry with the help of Henry Marc Brunel.",
                            ImageAltText = "An image of Tower Bridge in the evening.",
                            ImageUrl = "https://media.istockphoto.com/id/1337592981/photo/tower-bridge-in-the-evening-london-england-uk.jpg?b=1&s=170667a&w=0&k=20&c=W3wH2itHMImP3ZAEk_ZDk3UHopEQ7B_k4SJs-wGZEL8=",
                            Name = "Tower Bridge"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            Description = "The Avenue des Champs-Elysees is an avenue in the 8th arrondissement of Paris, France, 1.9 kilometres long and 70 metres wide, running between the Place de la Concorde in the east and the Place Charles de Gaulle in the west, where the Arc de Triomphe is located.",
                            ImageAltText = "An image of the Champs-Élysées taken at night.",
                            ImageUrl = "https://thumbs.dreamstime.com/b/champs-elysees-arc-de-triomphe-night-paris-champs-elysees-arc-de-triomphe-night-paris-france-107377207.jpg",
                            Name = "Champs-Elysees"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            Description = "The NASCAR Hall of Fame, located in Charlotte, North Carolina, honors drivers who have shown expert skill at NASCAR driving, all-time great crew chiefs and owners, broadcasters and other major contributors to competition within the sanctioning body.",
                            ImageAltText = "A picture of the NASCAR Hall of Fame building, in Charlotte, North Carolina.",
                            ImageUrl = "https://media.istockphoto.com/id/854657408/photo/nascar-hall-of-fame-in-charlotte-north-carolina-usa.jpg?s=612x612&w=0&k=20&c=5WNpQ-xkPjkUF8EQdVTw93fYsdmurJe4SRQf7m4kCmE=",
                            Name = "NASCAR Hall of Fame"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 5,
                            Description = "The Cromwell Museum in Huntingdon, England, is a museum containing collections exploring the life of Oliver Cromwell and to a lesser extent his son Richard Cromwell. Oliver Cromwell was born in Huntingdon in 1599 and lived there for more than half his life.",
                            ImageAltText = "A picture of the Cromwell Museum, taken outside.",
                            ImageUrl = "https://letsgowiththechildren.co.uk/wp-content/uploads/2022/03/cromwell-museum-915x515.jpg",
                            Name = "Cromwell Museum"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 6,
                            Description = "Aquarium with marine wildlife in tropical, temperate & polar zones, including 7 shark species.",
                            ImageAltText = "A picture taken from inside the aquarium, with a group of people enjoying the experience.",
                            ImageUrl = "https://www.brestaim-events.com/wp-content/uploads/2016/03/OCEANOPOLIS_1.jpg",
                            Name = "Oceanopolis"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.HasOne("CityInfo.API.Entities.City", "City")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Navigation("PointsOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
